export type ProductCategory = "llantas" | "lubricantes" | "baterias" | "rines";
export type ProductBadge    = "best-seller" | "flash-deal" | "new" | "hot";

export interface ProductSpec {
  key: string;
  value: string;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  badge?: ProductBadge;
  discountPct?: number;
  tags: string[];
  specs: string[];
  specsTable: ProductSpec[];
  inStock: boolean;
  stockCount: number;
  shortDesc: string;
  images?: string[];
  bgFrom: string;
  bgTo: string;
}

const IMG_TIRE_A = "https://scontent2.llantas.mx/images/508X636/models/Aurora_AT_698638317f909.jpg";
const IMG_TIRE_B = "https://interllantas.com/wp-content/uploads/images2/Llanta-COSMO-RC-17-185-65-R15-88H.jpg";
const IMG_OIL    = "https://www.terpel.com/var/site/storage/images/5/1/4/6/96415-1-esl-CO/f6b50119131d-OG.png";
const IMG_BAT    = "https://www.alkosto.com/medias/7707174439805-001-750Wx750H?context=bWFzdGVyfGltYWdlc3wzNDQ4OHxpbWFnZS93ZWJwfGFEbGpMMmczTXk4eE5UTTJOREE1T1RJM05qZ3pNQzgzTnpBM01UYzBORE01X0F3MVRJX05UQlhlRGMxTUVnfDc3ODFhNzc2ZTQ5ODk5YmYwNmExMDg3ZmU3MTVmYTdlMjFmNDk5ZmRhNzYyMzlkMjMwMjJhNzI2OTIzYTI4Njg";
const IMG_RIM    = "https://www.wheelcompany.com.co/public/images/item/1742263056.jpeg";

export const ALL_PRODUCTS: Product[] = [

  /* ── LLANTAS ─────────────────────────────────────────────────────── */

  // Continental
  {
    id: "continental-sportcontact7-22545r17",
    name: "Continental SportContact 7",
    brand: "Continental",
    category: "llantas",
    price: 620000,
    originalPrice: 730000,
    rating: 4.8,
    reviewCount: 1187,
    badge: "flash-deal",
    discountPct: 15,
    tags: ["UHP", "225/45 R17", "Performance"],
    specs: ["225/45 R17", "Performance", "94Y"],
    specsTable: [
      { key: "Medida",          value: "225/45 R17" },
      { key: "Índice de carga", value: "94" },
      { key: "Velocidad",       value: "Y (+300 km/h)" },
      { key: "Tipo",            value: "Ultra High Performance" },
      { key: "Temporada",       value: "Verano" },
      { key: "Origen",          value: "Alemania" },
    ],
    inStock: true,
    stockCount: 8,
    shortDesc: "Tecnología de Fórmula 1 aplicada a la calle. Máximo grip y precisión de dirección.",
    images: [IMG_TIRE_A],
    bgFrom: "#0d1117",
    bgTo: "#1a2234",
  },
  {
    id: "continental-crosscontact-23560r18",
    name: "Continental CrossContact LX 2",
    brand: "Continental",
    category: "llantas",
    price: 580000,
    rating: 4.7,
    reviewCount: 334,
    badge: "hot",
    tags: ["SUV", "235/60 R18", "Todo terreno"],
    specs: ["235/60 R18", "SUV", "107V"],
    specsTable: [
      { key: "Medida",    value: "235/60 R18" },
      { key: "Velocidad", value: "V (240 km/h)" },
      { key: "Uso",       value: "SUV / Crossover" },
      { key: "Origen",    value: "Alemania" },
    ],
    inStock: true,
    stockCount: 10,
    shortDesc: "Pensada para SUV modernos. Confort en asfalto y seguridad en caminos difíciles.",
    images: [IMG_TIRE_A],
    bgFrom: "#0d1117",
    bgTo: "#1a2234",
  },

  // Hankook
  {
    id: "hankook-ventus-s1evo3-22545r17",
    name: "Hankook Ventus S1 Evo3",
    brand: "Hankook",
    category: "llantas",
    price: 480000,
    originalPrice: 555000,
    rating: 4.7,
    reviewCount: 892,
    badge: "best-seller",
    discountPct: 14,
    tags: ["UHP", "225/45 R17", "Seco/Mojado"],
    specs: ["225/45 R17", "UHP", "91Y"],
    specsTable: [
      { key: "Medida",          value: "225/45 R17" },
      { key: "Índice de carga", value: "91" },
      { key: "Velocidad",       value: "Y (+300 km/h)" },
      { key: "Tipo",            value: "Ultra High Performance" },
      { key: "Origen",          value: "Corea del Sur" },
    ],
    inStock: true,
    stockCount: 14,
    shortDesc: "Alto rendimiento con excelente agarre en mojado. Favorito de los conductores exigentes.",
    images: [IMG_TIRE_A],
    bgFrom: "#0a0a1a",
    bgTo: "#14142d",
  },
  {
    id: "hankook-dynapro-at2-26570r16",
    name: "Hankook Dynapro AT2",
    brand: "Hankook",
    category: "llantas",
    price: 420000,
    rating: 4.6,
    reviewCount: 543,
    badge: "new",
    tags: ["A/T", "265/70 R16", "4x4"],
    specs: ["265/70 R16", "A/T", "112T"],
    specsTable: [
      { key: "Medida",    value: "265/70 R16" },
      { key: "Velocidad", value: "T (190 km/h)" },
      { key: "Tipo",      value: "All-Terrain" },
      { key: "Uso",       value: "SUV / Pick-up / 4x4" },
    ],
    inStock: true,
    stockCount: 18,
    shortDesc: "All-terrain de alto desempeño para SUV y camionetas. Resistencia superior al desgaste.",
    images: [IMG_TIRE_A],
    bgFrom: "#101a10",
    bgTo: "#1a2d1a",
  },

  // Aplus
  {
    id: "aplus-a609-18565r15",
    name: "Aplus A609",
    brand: "Aplus",
    category: "llantas",
    price: 165000,
    rating: 4.2,
    reviewCount: 318,
    tags: ["Eco", "185/65 R15", "Bajo consumo"],
    specs: ["185/65 R15", "Eco", "88H"],
    specsTable: [
      { key: "Medida",    value: "185/65 R15" },
      { key: "Velocidad", value: "H (210 km/h)" },
      { key: "Tipo",      value: "Ecológico" },
    ],
    inStock: true,
    stockCount: 35,
    shortDesc: "Bajo consumo y alta durabilidad a un precio accesible. La opción económica inteligente.",
    images: [IMG_TIRE_B],
    bgFrom: "#0f1a12",
    bgTo: "#1a2d1e",
  },
  {
    id: "aplus-radial-a-20555r16",
    name: "Aplus Radial A",
    brand: "Aplus",
    category: "llantas",
    price: 195000,
    originalPrice: 229000,
    rating: 4.3,
    reviewCount: 211,
    badge: "flash-deal",
    discountPct: 15,
    tags: ["Touring", "205/55 R16", "Silencioso"],
    specs: ["205/55 R16", "Touring", "91V"],
    specsTable: [
      { key: "Medida",    value: "205/55 R16" },
      { key: "Velocidad", value: "V (240 km/h)" },
      { key: "Tipo",      value: "Touring" },
    ],
    inStock: true,
    stockCount: 28,
    shortDesc: "Comodidad y economía para el uso urbano diario. Bajo nivel de ruido.",
    images: [IMG_TIRE_B],
    bgFrom: "#0f1a12",
    bgTo: "#1a2d1e",
  },

  // CargoPower
  {
    id: "cargopower-cp01-19565r15",
    name: "CargoPower CP-01",
    brand: "CargoPower",
    category: "llantas",
    price: 175000,
    rating: 4.1,
    reviewCount: 154,
    badge: "new",
    tags: ["Touring", "195/65 R15", "Carga"],
    specs: ["195/65 R15", "Carga", "91H"],
    specsTable: [
      { key: "Medida",    value: "195/65 R15" },
      { key: "Velocidad", value: "H (210 km/h)" },
      { key: "Tipo",      value: "Touring / Carga" },
    ],
    inStock: true,
    stockCount: 40,
    shortDesc: "Diseñada para vehículos de carga ligera. Alta resistencia a la deformación.",
    images: [IMG_TIRE_B],
    bgFrom: "#1a0d00",
    bgTo: "#2d1a00",
  },
  {
    id: "cargopower-cb02-21565r16",
    name: "CargoPower CB-02",
    brand: "CargoPower",
    category: "llantas",
    price: 210000,
    rating: 4.2,
    reviewCount: 98,
    tags: ["SUV", "215/65 R16", "Carga"],
    specs: ["215/65 R16", "SUV", "98H"],
    specsTable: [
      { key: "Medida",    value: "215/65 R16" },
      { key: "Velocidad", value: "H (210 km/h)" },
      { key: "Uso",       value: "SUV / Carga media" },
    ],
    inStock: true,
    stockCount: 22,
    shortDesc: "Para SUV y furgonetas. Excelente capacidad de carga con manejo estable.",
    images: [IMG_TIRE_B],
    bgFrom: "#1a0d00",
    bgTo: "#2d1a00",
  },

  // Tab
  {
    id: "tab-speed-19555r15",
    name: "Tab Speed",
    brand: "Tab",
    category: "llantas",
    price: 155000,
    rating: 4.0,
    reviewCount: 187,
    tags: ["Touring", "195/55 R15", "Urbano"],
    specs: ["195/55 R15", "Touring", "85V"],
    specsTable: [
      { key: "Medida",    value: "195/55 R15" },
      { key: "Velocidad", value: "V (240 km/h)" },
      { key: "Tipo",      value: "Touring" },
    ],
    inStock: true,
    stockCount: 45,
    shortDesc: "Llanta urbana de calidad a precio competitivo. Buena adherencia en pavimento mojado.",
    images: [IMG_TIRE_B],
    bgFrom: "#1a1200",
    bgTo: "#2d1e00",
  },
  {
    id: "tab-hp-22545r17",
    name: "Tab Total HP",
    brand: "Tab",
    category: "llantas",
    price: 245000,
    originalPrice: 285000,
    rating: 4.3,
    reviewCount: 134,
    badge: "flash-deal",
    discountPct: 14,
    tags: ["HP", "225/45 R17", "Performance"],
    specs: ["225/45 R17", "HP", "91W"],
    specsTable: [
      { key: "Medida",    value: "225/45 R17" },
      { key: "Velocidad", value: "W (270 km/h)" },
      { key: "Tipo",      value: "High Performance" },
    ],
    inStock: true,
    stockCount: 16,
    shortDesc: "Rendimiento deportivo sin sacrificar el bolsillo. Buena respuesta en curvas.",
    images: [IMG_TIRE_A],
    bgFrom: "#1a1200",
    bgTo: "#2d1e00",
  },

  // Nexen
  {
    id: "nexen-nfera-su1-21555r17",
    name: "Nexen N'Fera SU1",
    brand: "Nexen",
    category: "llantas",
    price: 285000,
    rating: 4.4,
    reviewCount: 228,
    badge: "new",
    tags: ["UHP", "215/55 R17", "Performance"],
    specs: ["215/55 R17", "UHP", "98W"],
    specsTable: [
      { key: "Medida",    value: "215/55 R17" },
      { key: "Velocidad", value: "W (270 km/h)" },
      { key: "Tipo",      value: "High Performance" },
    ],
    inStock: true,
    stockCount: 16,
    shortDesc: "Rendimiento de alta velocidad con excelente relación calidad-precio.",
    images: [IMG_TIRE_A],
    bgFrom: "#101520",
    bgTo: "#1a2033",
  },
  {
    id: "nexen-roadian-at-pro-26570r16",
    name: "Nexen Roadian AT Pro",
    brand: "Nexen",
    category: "llantas",
    price: 320000,
    rating: 4.5,
    reviewCount: 301,
    badge: "best-seller",
    tags: ["A/T", "265/70 R16", "SUV"],
    specs: ["265/70 R16", "A/T", "112T"],
    specsTable: [
      { key: "Medida",    value: "265/70 R16" },
      { key: "Velocidad", value: "T (190 km/h)" },
      { key: "Tipo",      value: "All-Terrain" },
      { key: "Uso",       value: "SUV / Camionetas" },
    ],
    inStock: true,
    stockCount: 20,
    shortDesc: "Ideal para SUV y camionetas que mezclan carretera con campo. Alta resistencia.",
    images: [IMG_TIRE_A],
    bgFrom: "#101520",
    bgTo: "#1a2033",
  },

  /* ── LUBRICANTES ──────────────────────────────────────────────────── */

  // Mobil
  {
    id: "mobil1-5w30-4l",
    name: "Mobil 1 Sintético 5W-30",
    brand: "Mobil",
    category: "lubricantes",
    price: 95000,
    originalPrice: 115000,
    rating: 4.9,
    reviewCount: 3456,
    badge: "best-seller",
    discountPct: 17,
    tags: ["5W-30", "Sintético", "4L"],
    specs: ["5W-30", "4L", "Full Sintético"],
    specsTable: [
      { key: "Viscosidad",  value: "5W-30" },
      { key: "Volumen",     value: "4 Litros" },
      { key: "Tipo",        value: "100% Sintético" },
      { key: "Norma API",   value: "SP" },
      { key: "Aplicación",  value: "Gasolina" },
    ],
    inStock: true,
    stockCount: 45,
    shortDesc: "Protección líder en la industria para motores de gasolina modernos.",
    images: [IMG_OIL],
    bgFrom: "#1a0d00",
    bgTo: "#2d1a00",
  },
  {
    id: "mobil-super3000-10w40-4l",
    name: "Mobil Super 3000 10W-40",
    brand: "Mobil",
    category: "lubricantes",
    price: 55000,
    rating: 4.5,
    reviewCount: 987,
    tags: ["10W-40", "Semi-Sintético", "4L"],
    specs: ["10W-40", "4L", "Semi-Sintético"],
    specsTable: [
      { key: "Viscosidad",  value: "10W-40" },
      { key: "Volumen",     value: "4 Litros" },
      { key: "Tipo",        value: "Semi-Sintético" },
      { key: "Norma API",   value: "SN" },
    ],
    inStock: true,
    stockCount: 52,
    shortDesc: "Elección inteligente para motores con alto kilometraje que buscan protección avanzada.",
    images: [IMG_OIL],
    bgFrom: "#1a0d00",
    bgTo: "#2d1a00",
  },

  // Total
  {
    id: "total-quartz9000-5w40-4l",
    name: "Total Quartz 9000 5W-40",
    brand: "Total",
    category: "lubricantes",
    price: 88000,
    rating: 4.7,
    reviewCount: 1102,
    badge: "hot",
    tags: ["5W-40", "Sintético", "4L"],
    specs: ["5W-40", "4L", "Full Sintético"],
    specsTable: [
      { key: "Viscosidad",  value: "5W-40" },
      { key: "Volumen",     value: "4 Litros" },
      { key: "Tipo",        value: "100% Sintético" },
      { key: "Norma API",   value: "SN Plus" },
    ],
    inStock: true,
    stockCount: 30,
    shortDesc: "Formulado con tecnología Future Fluid para protección máxima en frío y calor.",
    images: [IMG_OIL],
    bgFrom: "#00101a",
    bgTo: "#001a2d",
  },
  {
    id: "total-quartz7000-10w40-4l",
    name: "Total Quartz 7000 10W-40",
    brand: "Total",
    category: "lubricantes",
    price: 52000,
    originalPrice: 62000,
    rating: 4.4,
    reviewCount: 678,
    badge: "flash-deal",
    discountPct: 16,
    tags: ["10W-40", "Semi-Sintético", "4L"],
    specs: ["10W-40", "4L", "Semi-Sintético"],
    specsTable: [
      { key: "Viscosidad",  value: "10W-40" },
      { key: "Volumen",     value: "4 Litros" },
      { key: "Tipo",        value: "Semi-Sintético" },
    ],
    inStock: true,
    stockCount: 60,
    shortDesc: "Protección confiable para uso cotidiano. Compatible con la mayoría de motores gasolina.",
    images: [IMG_OIL],
    bgFrom: "#00101a",
    bgTo: "#001a2d",
  },

  // Rubia
  {
    id: "rubia-tir8600-15w40-5l",
    name: "Rubia TIR 8600 15W-40",
    brand: "Rubia",
    category: "lubricantes",
    price: 72000,
    rating: 4.6,
    reviewCount: 543,
    badge: "new",
    tags: ["15W-40", "Diesel", "5L"],
    specs: ["15W-40", "5L", "Diésel"],
    specsTable: [
      { key: "Viscosidad",  value: "15W-40" },
      { key: "Volumen",     value: "5 Litros" },
      { key: "Tipo",        value: "Mineral reforzado" },
      { key: "Motor",       value: "Diésel" },
      { key: "Norma ACEA",  value: "E7" },
    ],
    inStock: true,
    stockCount: 28,
    shortDesc: "Aceite de motor diésel para flotas y camiones. Prolonga la vida útil del motor.",
    images: [IMG_OIL],
    bgFrom: "#1a0505",
    bgTo: "#2d0a0a",
  },
  {
    id: "rubia-s-10w40-4l",
    name: "Rubia S 10W-40",
    brand: "Rubia",
    category: "lubricantes",
    price: 48000,
    rating: 4.3,
    reviewCount: 312,
    tags: ["10W-40", "Diésel", "4L"],
    specs: ["10W-40", "4L", "Semi-Sintético"],
    specsTable: [
      { key: "Viscosidad",  value: "10W-40" },
      { key: "Volumen",     value: "4 Litros" },
      { key: "Tipo",        value: "Semi-Sintético" },
      { key: "Motor",       value: "Diésel / Gasolina" },
    ],
    inStock: true,
    stockCount: 35,
    shortDesc: "Aceite polivalente diésel-gasolina. Ideal para mecánica general y uso mixto.",
    images: [IMG_OIL],
    bgFrom: "#1a0505",
    bgTo: "#2d0a0a",
  },

  /* ── BATERÍAS ─────────────────────────────────────────────────────── */

  // Willard
  {
    id: "willard-500-55ah",
    name: "Willard 500 55Ah",
    brand: "Willard",
    category: "baterias",
    price: 245000,
    rating: 4.4,
    reviewCount: 589,
    tags: ["55Ah", "12V", "Libre mantenimiento"],
    specs: ["55Ah", "12V", "Libre mantenimiento"],
    specsTable: [
      { key: "Capacidad",  value: "55 Ah" },
      { key: "Voltaje",    value: "12V" },
      { key: "CCA",        value: "460A" },
      { key: "Tipo",       value: "Libre mantenimiento" },
      { key: "Garantía",   value: "12 meses" },
    ],
    inStock: true,
    stockCount: 28,
    shortDesc: "Marca colombiana de confianza. Excelente relación precio-rendimiento para autos compactos.",
    images: [IMG_BAT],
    bgFrom: "#10001a",
    bgTo: "#1a002d",
  },
  {
    id: "willard-600-60ah",
    name: "Willard 600 60Ah",
    brand: "Willard",
    category: "baterias",
    price: 285000,
    originalPrice: 325000,
    rating: 4.6,
    reviewCount: 812,
    badge: "best-seller",
    discountPct: 12,
    tags: ["60Ah", "12V", "Libre mantenimiento"],
    specs: ["60Ah", "12V", "Libre mantenimiento"],
    specsTable: [
      { key: "Capacidad",  value: "60 Ah" },
      { key: "Voltaje",    value: "12V" },
      { key: "CCA",        value: "540A" },
      { key: "Tipo",       value: "Libre mantenimiento" },
      { key: "Garantía",   value: "18 meses" },
    ],
    inStock: true,
    stockCount: 20,
    shortDesc: "La batería más vendida de Colombia. Compatible con sedanes y SUV de uso intensivo.",
    images: [IMG_BAT],
    bgFrom: "#10001a",
    bgTo: "#1a002d",
  },
  {
    id: "willard-800-72ah",
    name: "Willard 800 72Ah AGM",
    brand: "Willard",
    category: "baterias",
    price: 370000,
    rating: 4.8,
    reviewCount: 445,
    badge: "flash-deal",
    tags: ["72Ah", "12V", "AGM"],
    specs: ["72Ah", "12V", "AGM"],
    specsTable: [
      { key: "Capacidad",  value: "72 Ah" },
      { key: "Voltaje",    value: "12V" },
      { key: "CCA",        value: "720A" },
      { key: "Tipo",       value: "AGM – Absorbent Glass Mat" },
      { key: "Garantía",   value: "24 meses" },
    ],
    inStock: true,
    stockCount: 12,
    shortDesc: "Tecnología AGM para vehículos con Start-Stop. Soporta ciclos profundos de descarga.",
    images: [IMG_BAT],
    bgFrom: "#10001a",
    bgTo: "#1a002d",
  },
  {
    id: "willard-900-80ah",
    name: "Willard 900 80Ah",
    brand: "Willard",
    category: "baterias",
    price: 420000,
    rating: 4.7,
    reviewCount: 198,
    badge: "new",
    tags: ["80Ah", "12V", "Alta potencia"],
    specs: ["80Ah", "12V", "Alta potencia"],
    specsTable: [
      { key: "Capacidad",  value: "80 Ah" },
      { key: "Voltaje",    value: "12V" },
      { key: "CCA",        value: "780A" },
      { key: "Tipo",       value: "Libre mantenimiento" },
      { key: "Garantía",   value: "24 meses" },
    ],
    inStock: true,
    stockCount: 8,
    shortDesc: "Para SUV grandes y camionetas. Alta potencia de arranque incluso en climas fríos.",
    images: [IMG_BAT],
    bgFrom: "#10001a",
    bgTo: "#1a002d",
  },

  /* ── RINES ────────────────────────────────────────────────────────── */

  // Alcoa
  {
    id: "alcoa-ultraone-17",
    name: "Alcoa Ultra One 17\"",
    brand: "Alcoa",
    category: "rines",
    price: 520000,
    rating: 4.7,
    reviewCount: 234,
    badge: "new",
    tags: ["17\"", "Forjado", "5x114.3"],
    specs: ["17\"", "5x114.3", "Aluminio forjado"],
    specsTable: [
      { key: "Diámetro",  value: "17 pulgadas" },
      { key: "Ancho",     value: "7.5J" },
      { key: "Patrón",    value: "5x114.3" },
      { key: "Offset",    value: "ET45" },
      { key: "Material",  value: "Aluminio forjado" },
      { key: "Peso",      value: "8.2 kg" },
    ],
    inStock: true,
    stockCount: 8,
    shortDesc: "Rin de aluminio forjado Alcoa de alta pureza. Ligero, resistente y de acabado impecable.",
    images: [IMG_RIM],
    bgFrom: "#141414",
    bgTo: "#202020",
  },
  {
    id: "alcoa-ultraone-18",
    name: "Alcoa Ultra One 18\"",
    brand: "Alcoa",
    category: "rines",
    price: 680000,
    originalPrice: 790000,
    rating: 4.8,
    reviewCount: 187,
    badge: "flash-deal",
    discountPct: 14,
    tags: ["18\"", "Forjado", "5x120"],
    specs: ["18\"", "5x120", "Aluminio forjado"],
    specsTable: [
      { key: "Diámetro",  value: "18 pulgadas" },
      { key: "Ancho",     value: "8J" },
      { key: "Patrón",    value: "5x120" },
      { key: "Offset",    value: "ET48" },
      { key: "Material",  value: "Aluminio forjado" },
    ],
    inStock: true,
    stockCount: 6,
    shortDesc: "Diseño deportivo con forja de alta tecnología para SUV y sedanes premium.",
    images: [IMG_RIM],
    bgFrom: "#141414",
    bgTo: "#202020",
  },
  {
    id: "alcoa-forged-20",
    name: "Alcoa Forged 20\"",
    brand: "Alcoa",
    category: "rines",
    price: 920000,
    rating: 4.9,
    reviewCount: 112,
    badge: "hot",
    tags: ["20\"", "Forjado", "5x112"],
    specs: ["20\"", "5x112", "Aluminio forjado"],
    specsTable: [
      { key: "Diámetro",  value: "20 pulgadas" },
      { key: "Ancho",     value: "9J" },
      { key: "Patrón",    value: "5x112" },
      { key: "Offset",    value: "ET35" },
      { key: "Material",  value: "Aluminio forjado A356" },
    ],
    inStock: true,
    stockCount: 4,
    shortDesc: "Para SUV y 4x4 de lujo. El rin Alcoa más ligero por tamaño. Máxima rigidez estructural.",
    images: [IMG_RIM],
    bgFrom: "#141414",
    bgTo: "#202020",
  },
  {
    id: "alcoa-durabright-225",
    name: "Alcoa Dura-Bright 22.5\"",
    brand: "Alcoa",
    category: "rines",
    price: 850000,
    rating: 4.6,
    reviewCount: 89,
    badge: "new",
    tags: ["22.5\"", "Camión", "Alcoa EVO"],
    specs: ["22.5\"", "10x335", "Dura-Bright EVO"],
    specsTable: [
      { key: "Diámetro",   value: "22.5 pulgadas" },
      { key: "Ancho",      value: "8.25\"" },
      { key: "Uso",        value: "Camiones y tractomulas" },
      { key: "Acabado",    value: "Dura-Bright EVO (sin pulir)" },
    ],
    inStock: true,
    stockCount: 10,
    shortDesc: "El rin de aluminio estándar para flota pesada. Ahorra peso y reduce consumo de combustible.",
    images: [IMG_RIM],
    bgFrom: "#141414",
    bgTo: "#202020",
  },
];

/* ── Helpers ─────────────────────────────────────────────────────────── */
export function getProductById(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return ALL_PRODUCTS.filter((p) => p.category === category);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return ALL_PRODUCTS
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  llantas:     "Llantas",
  lubricantes: "Lubricantes",
  baterias:    "Baterías",
  rines:       "Rines",
};
