export type ProductCategory = "llantas" | "lubricantes" | "baterias" | "rines" | "accesorios";
export type ProductBadge    = "best-seller" | "flash-deal" | "new" | "hot";

export interface ProductSpec {
  key: string;
  value: string;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  badge?: ProductBadge;
  discountPct?: number;
  tags: string[];
  specs: string[];              // short display chips
  specsTable: ProductSpec[];    // full detail table
  inStock: boolean;
  stockCount: number;
  shortDesc: string;
  images?: string[];            // real product photos (optional)
  bgFrom: string;               // gradient for placeholder image
  bgTo: string;
}

export const ALL_PRODUCTS: Product[] = [
  /* ── LLANTAS ─────────────────────────────────────────────────────── */
  {
    id: "michelin-primacy4-20555r16",
    name: "Michelin Primacy 4",
    brand: "Michelin",
    category: "llantas",
    price: 480000,
    originalPrice: 565000,
    rating: 4.9,
    reviewCount: 2341,
    badge: "best-seller",
    discountPct: 15,
    tags: ["Touring", "205/55 R16", "Bajo ruido"],
    specs: ["205/55 R16", "Touring", "91W"],
    specsTable: [
      { key: "Medida",        value: "205/55 R16" },
      { key: "Índice de carga", value: "91" },
      { key: "Velocidad",     value: "W (270 km/h)" },
      { key: "Tipo",          value: "Touring" },
      { key: "Temporada",     value: "Todo el año" },
      { key: "Origen",        value: "Francia" },
    ],
    inStock: true,
    stockCount: 14,
    shortDesc: "Máxima adherencia en mojado. Ideal para uso urbano e interurbano intensivo.",
    bgFrom: "#1a1a1a",
    bgTo: "#2d2d2d",
  },
  {
    id: "continental-sportcontact7-22545r17",
    name: "Continental SportContact 7",
    brand: "Continental",
    category: "llantas",
    price: 620000,
    originalPrice: 730000,
    rating: 4.8,
    reviewCount: 1187,
    badge: "flash-deal",
    discountPct: 15,
    tags: ["UHP", "225/45 R17", "Performance"],
    specs: ["225/45 R17", "Performance", "94Y"],
    specsTable: [
      { key: "Medida",        value: "225/45 R17" },
      { key: "Índice de carga", value: "94" },
      { key: "Velocidad",     value: "Y (+300 km/h)" },
      { key: "Tipo",          value: "Ultra High Performance" },
      { key: "Temporada",     value: "Verano" },
      { key: "Origen",        value: "Alemania" },
    ],
    inStock: true,
    stockCount: 8,
    shortDesc: "Tecnología de Fórmula 1 aplicada a la calle. Máximo grip y precisión de dirección.",
    bgFrom: "#0d1117",
    bgTo: "#1a2234",
  },
  {
    id: "bridgestone-dueler-at-26570r16",
    name: "Bridgestone Dueler A/T",
    brand: "Bridgestone",
    category: "llantas",
    price: 540000,
    rating: 4.7,
    reviewCount: 876,
    badge: "hot",
    tags: ["A/T", "265/70 R16", "4x4"],
    specs: ["265/70 R16", "A/T", "112T"],
    specsTable: [
      { key: "Medida",        value: "265/70 R16" },
      { key: "Índice de carga", value: "112" },
      { key: "Velocidad",     value: "T (190 km/h)" },
      { key: "Tipo",          value: "All-Terrain" },
      { key: "Uso",           value: "SUV / Camionetas" },
      { key: "Origen",        value: "Japón" },
    ],
    inStock: true,
    stockCount: 20,
    shortDesc: "Diseñada para rendir tanto en ciudad como en campo. Tracción superior en superficies mixtas.",
    bgFrom: "#1a1010",
    bgTo: "#2d1a1a",
  },
  {
    id: "goodyear-wrangler-at-24570r16",
    name: "Goodyear Wrangler A/T",
    brand: "Goodyear",
    category: "llantas",
    price: 498000,
    originalPrice: 580000,
    rating: 4.6,
    reviewCount: 654,
    badge: "flash-deal",
    discountPct: 14,
    tags: ["A/T", "245/70 R16", "SUV"],
    specs: ["245/70 R16", "A/T", "107T"],
    specsTable: [
      { key: "Medida",        value: "245/70 R16" },
      { key: "Índice de carga", value: "107" },
      { key: "Velocidad",     value: "T (190 km/h)" },
      { key: "Tipo",          value: "All-Terrain" },
      { key: "Uso",           value: "SUV / Pick-up" },
      { key: "Origen",        value: "USA" },
    ],
    inStock: true,
    stockCount: 12,
    shortDesc: "Rendimiento todoterreno con comodidad en carretera. Excelente durabilidad.",
    bgFrom: "#111820",
    bgTo: "#1a2535",
  },
  {
    id: "pirelli-pzero-25540r18",
    name: "Pirelli P Zero",
    brand: "Pirelli",
    category: "llantas",
    price: 750000,
    rating: 4.9,
    reviewCount: 2109,
    badge: "hot",
    tags: ["UHP", "255/40 R18", "Seco"],
    specs: ["255/40 R18", "UHP", "99Y"],
    specsTable: [
      { key: "Medida",        value: "255/40 R18" },
      { key: "Índice de carga", value: "99" },
      { key: "Velocidad",     value: "Y (+300 km/h)" },
      { key: "Tipo",          value: "Ultra High Performance" },
      { key: "Temporada",     value: "Verano" },
      { key: "Origen",        value: "Italia" },
    ],
    inStock: true,
    stockCount: 6,
    shortDesc: "Equipamiento de fábrica en los mejores deportivos del mundo. Neumático de referencia.",
    bgFrom: "#1a0a0a",
    bgTo: "#2d1212",
  },
  {
    id: "michelin-pilot-sport4-23535r19",
    name: "Michelin Pilot Sport 4",
    brand: "Michelin",
    category: "llantas",
    price: 890000,
    rating: 4.9,
    reviewCount: 981,
    badge: "new",
    tags: ["Sport", "235/35 R19", "Seco/Mojado"],
    specs: ["235/35 R19", "Sport", "91Y"],
    specsTable: [
      { key: "Medida",        value: "235/35 R19" },
      { key: "Índice de carga", value: "91" },
      { key: "Velocidad",     value: "Y (+300 km/h)" },
      { key: "Tipo",          value: "Sport" },
      { key: "Temporada",     value: "Verano" },
    ],
    inStock: true,
    stockCount: 4,
    shortDesc: "El referente de rendimiento deportivo para quienes exigen lo mejor.",
    bgFrom: "#1a1a1a",
    bgTo: "#2d2d2d",
  },
  {
    id: "bridgestone-turanza-t005-19565r15",
    name: "Bridgestone Turanza T005",
    brand: "Bridgestone",
    category: "llantas",
    price: 310000,
    originalPrice: 360000,
    rating: 4.6,
    reviewCount: 445,
    badge: "flash-deal",
    discountPct: 14,
    tags: ["Touring", "195/65 R15", "Mojado"],
    specs: ["195/65 R15", "Touring", "91V"],
    specsTable: [
      { key: "Medida",        value: "195/65 R15" },
      { key: "Índice de carga", value: "91" },
      { key: "Velocidad",     value: "V (240 km/h)" },
      { key: "Tipo",          value: "Touring" },
    ],
    inStock: true,
    stockCount: 22,
    shortDesc: "Excelente frenado en mojado y bajo nivel de ruido para el uso diario.",
    bgFrom: "#101a10",
    bgTo: "#1a2d1a",
  },
  {
    id: "kumho-ecowing-18565r15",
    name: "Kumho Ecowing ES31",
    brand: "Kumho",
    category: "llantas",
    price: 185000,
    rating: 4.3,
    reviewCount: 312,
    tags: ["Eco", "185/65 R15", "Bajo consumo"],
    specs: ["185/65 R15", "Eco", "88T"],
    specsTable: [
      { key: "Medida",        value: "185/65 R15" },
      { key: "Velocidad",     value: "T (190 km/h)" },
      { key: "Tipo",          value: "Ecológico" },
    ],
    inStock: true,
    stockCount: 30,
    shortDesc: "Bajo consumo de combustible y baja emisión de CO₂. La opción económica y responsable.",
    images: [
      "https://interllantas.com/wp-content/uploads/images2/Llanta-COSMO-RC-17-185-65-R15-88H.jpg",
      "https://interllantas.com/wp-content/uploads/images2/Llanta-COSMO-RC-17-185-65-R15-88H_2.jpg",
      "https://interllantas.com/wp-content/uploads/images2/Llanta-COSMO-RC-17-185-65-R15-88H_1.jpg",
    ],
    bgFrom: "#0f1a12",
    bgTo: "#1a2d1e",
  },
  {
    id: "nexen-nfera-su1-21555r17",
    name: "Nexen N'Fera SU1",
    brand: "Nexen",
    category: "llantas",
    price: 285000,
    rating: 4.4,
    reviewCount: 228,
    badge: "new",
    tags: ["UHP", "215/55 R17", "Performance"],
    specs: ["215/55 R17", "UHP", "98W"],
    specsTable: [
      { key: "Medida",        value: "215/55 R17" },
      { key: "Velocidad",     value: "W (270 km/h)" },
      { key: "Tipo",          value: "High Performance" },
    ],
    inStock: true,
    stockCount: 16,
    shortDesc: "Rendimiento de alta velocidad con excelente relación calidad-precio.",
    bgFrom: "#101520",
    bgTo: "#1a2033",
  },
  {
    id: "continental-crosscontact-23560r18",
    name: "Continental CrossContact LX",
    brand: "Continental",
    category: "llantas",
    price: 580000,
    rating: 4.7,
    reviewCount: 334,
    tags: ["SUV", "235/60 R18", "Todo terreno"],
    specs: ["235/60 R18", "SUV", "107V"],
    specsTable: [
      { key: "Medida",        value: "235/60 R18" },
      { key: "Velocidad",     value: "V (240 km/h)" },
      { key: "Uso",           value: "SUV / Crossover" },
    ],
    inStock: true,
    stockCount: 10,
    shortDesc: "Pensada para SUV modernos. Confort en asfalto y seguridad en caminos difíciles.",
    bgFrom: "#0d1117",
    bgTo: "#1a2234",
  },

  /* ── LUBRICANTES ─────────────────────────────────────────────────── */
  {
    id: "mobil1-5w30-4l",
    name: "Mobil 1 Sintético 5W-30",
    brand: "Mobil",
    category: "lubricantes",
    price: 95000,
    originalPrice: 115000,
    rating: 4.9,
    reviewCount: 3456,
    badge: "best-seller",
    discountPct: 17,
    tags: ["5W-30", "Sintético", "4L"],
    specs: ["5W-30", "4L", "Full Sintético"],
    specsTable: [
      { key: "Viscosidad",    value: "5W-30" },
      { key: "Volumen",       value: "4 Litros" },
      { key: "Tipo",          value: "100% Sintético" },
      { key: "Norma API",     value: "SP" },
      { key: "Aplicación",    value: "Gasolina" },
    ],
    inStock: true,
    stockCount: 45,
    shortDesc: "Protección líder en la industria para motores de gasolina modernos.",
    bgFrom: "#1a0d00",
    bgTo: "#2d1a00",
  },
  {
    id: "castrol-edge-5w40-4l",
    name: "Castrol EDGE 5W-40",
    brand: "Castrol",
    category: "lubricantes",
    price: 88000,
    rating: 4.8,
    reviewCount: 1890,
    badge: "hot",
    tags: ["5W-40", "Sintético", "4L"],
    specs: ["5W-40", "4L", "Full Sintético"],
    specsTable: [
      { key: "Viscosidad",    value: "5W-40" },
      { key: "Volumen",       value: "4 Litros" },
      { key: "Tipo",          value: "100% Sintético" },
      { key: "Norma API",     value: "SN Plus" },
    ],
    inStock: true,
    stockCount: 38,
    shortDesc: "Tecnología TITANIUM FST para reducir la fricción y proteger el motor incluso bajo presión extrema.",
    bgFrom: "#1a0505",
    bgTo: "#2d0a0a",
  },
  {
    id: "shell-helix-5w40-4l",
    name: "Shell Helix Ultra 5W-40",
    brand: "Shell",
    category: "lubricantes",
    price: 92000,
    originalPrice: 108000,
    rating: 4.7,
    reviewCount: 1234,
    badge: "flash-deal",
    discountPct: 15,
    tags: ["5W-40", "Sintético", "4L"],
    specs: ["5W-40", "4L", "Full Sintético"],
    specsTable: [
      { key: "Viscosidad",    value: "5W-40" },
      { key: "Volumen",       value: "4 Litros" },
      { key: "Tipo",          value: "100% Sintético" },
    ],
    inStock: true,
    stockCount: 24,
    shortDesc: "Desarrollado con tecnología PurePlus: gas natural convertido en aceite base puro.",
    bgFrom: "#1a1200",
    bgTo: "#2d1e00",
  },
  {
    id: "mobil-super3000-10w40-4l",
    name: "Mobil Super 3000 10W-40",
    brand: "Mobil",
    category: "lubricantes",
    price: 55000,
    rating: 4.5,
    reviewCount: 987,
    tags: ["10W-40", "Semi-Sintético", "4L"],
    specs: ["10W-40", "4L", "Semi-Sintético"],
    specsTable: [
      { key: "Viscosidad",    value: "10W-40" },
      { key: "Volumen",       value: "4 Litros" },
      { key: "Tipo",          value: "Semi-Sintético" },
    ],
    inStock: true,
    stockCount: 52,
    shortDesc: "La elección inteligente para motores con alto kilometraje que buscan protección avanzada.",
    bgFrom: "#1a0d00",
    bgTo: "#2d1a00",
  },
  {
    id: "valvoline-synpower-5w30-4l",
    name: "Valvoline SynPower 5W-30",
    brand: "Valvoline",
    category: "lubricantes",
    price: 78000,
    rating: 4.6,
    reviewCount: 678,
    badge: "new",
    tags: ["5W-30", "Sintético", "4L"],
    specs: ["5W-30", "4L", "Full Sintético"],
    specsTable: [
      { key: "Viscosidad",    value: "5W-30" },
      { key: "Volumen",       value: "4 Litros" },
      { key: "Tipo",          value: "100% Sintético" },
    ],
    inStock: true,
    stockCount: 18,
    shortDesc: "Formulado con aditivos avanzados que limpian y protegen el motor en todo momento.",
    bgFrom: "#001a0d",
    bgTo: "#002d1a",
  },

  /* ── BATERÍAS ─────────────────────────────────────────────────────── */
  {
    id: "bosch-s4-60ah",
    name: "Batería Bosch S4 60Ah",
    brand: "Bosch",
    category: "baterias",
    price: 320000,
    originalPrice: 380000,
    rating: 4.8,
    reviewCount: 1023,
    badge: "flash-deal",
    discountPct: 16,
    tags: ["60Ah", "12V", "Libre mantenimiento"],
    specs: ["60Ah", "12V", "Libre mantenimiento"],
    specsTable: [
      { key: "Capacidad",     value: "60 Ah" },
      { key: "Voltaje",       value: "12V" },
      { key: "CCA",           value: "540A" },
      { key: "Tipo",          value: "Libre mantenimiento" },
      { key: "Garantía",      value: "18 meses" },
    ],
    inStock: true,
    stockCount: 15,
    shortDesc: "Arranque confiable en cualquier condición. Compatible con la mayoría de sedanes y SUV.",
    bgFrom: "#00101a",
    bgTo: "#001a2d",
  },
  {
    id: "bosch-s5-72ah",
    name: "Batería Bosch S5 72Ah",
    brand: "Bosch",
    category: "baterias",
    price: 385000,
    rating: 4.9,
    reviewCount: 567,
    badge: "best-seller",
    tags: ["72Ah", "12V", "AGM"],
    specs: ["72Ah", "12V", "AGM"],
    specsTable: [
      { key: "Capacidad",     value: "72 Ah" },
      { key: "Voltaje",       value: "12V" },
      { key: "CCA",           value: "720A" },
      { key: "Tipo",          value: "AGM – Absorbent Glass Mat" },
      { key: "Garantía",      value: "24 meses" },
    ],
    inStock: true,
    stockCount: 9,
    shortDesc: "Tecnología AGM para vehículos con sistema Start-Stop. Ciclos profundos de descarga.",
    bgFrom: "#00101a",
    bgTo: "#001a2d",
  },
  {
    id: "willard-500-55ah",
    name: "Willard 500 55Ah",
    brand: "Willard",
    category: "baterias",
    price: 280000,
    rating: 4.4,
    reviewCount: 312,
    tags: ["55Ah", "12V", "Libre mantenimiento"],
    specs: ["55Ah", "12V", "Libre mantenimiento"],
    specsTable: [
      { key: "Capacidad",     value: "55 Ah" },
      { key: "Voltaje",       value: "12V" },
      { key: "Tipo",          value: "Libre mantenimiento" },
      { key: "Garantía",      value: "12 meses" },
    ],
    inStock: true,
    stockCount: 20,
    shortDesc: "Marca colombiana de confianza. Excelente relación precio-rendimiento.",
    bgFrom: "#10001a",
    bgTo: "#1a002d",
  },
  {
    id: "motorcraft-70ah",
    name: "Motorcraft BXT70 70Ah",
    brand: "Motorcraft",
    category: "baterias",
    price: 340000,
    rating: 4.6,
    reviewCount: 198,
    badge: "new",
    tags: ["70Ah", "12V", "Ford Compatible"],
    specs: ["70Ah", "12V", "Libre mantenimiento"],
    specsTable: [
      { key: "Capacidad",     value: "70 Ah" },
      { key: "CCA",           value: "630A" },
      { key: "Tipo",          value: "Libre mantenimiento" },
    ],
    inStock: true,
    stockCount: 7,
    shortDesc: "Batería original Ford. Compatibilidad perfecta con todos los modelos de la marca.",
    bgFrom: "#001018",
    bgTo: "#001a28",
  },

  /* ── RINES ───────────────────────────────────────────────────────── */
  {
    id: "bbs-chr-17",
    name: "Rines BBS CH-R 17\"",
    brand: "BBS",
    category: "rines",
    price: 890000,
    rating: 4.9,
    reviewCount: 445,
    badge: "new",
    tags: ["17\"", "Forjado", "5x114.3"],
    specs: ["17\"", "5x114.3", "Aluminio forjado"],
    specsTable: [
      { key: "Diámetro",      value: "17 pulgadas" },
      { key: "Ancho",         value: "7.5J" },
      { key: "Patrón",        value: "5x114.3" },
      { key: "Offset",        value: "ET48" },
      { key: "Material",      value: "Aluminio forjado" },
      { key: "Peso",          value: "7.5 kg/ud" },
    ],
    inStock: true,
    stockCount: 4,
    shortDesc: "El rin más reconocido del motorsport. Construcción en aluminio forjado, ligereza extrema.",
    bgFrom: "#141414",
    bgTo: "#202020",
  },
  {
    id: "oz-superturismo-16",
    name: "OZ Superturismo GT 16\"",
    brand: "OZ Racing",
    category: "rines",
    price: 680000,
    rating: 4.7,
    reviewCount: 234,
    badge: "hot",
    tags: ["16\"", "Racing", "5x112"],
    specs: ["16\"", "5x112", "Aluminio fundido"],
    specsTable: [
      { key: "Diámetro",      value: "16 pulgadas" },
      { key: "Patrón",        value: "5x112" },
      { key: "Material",      value: "Aluminio fundido" },
    ],
    inStock: true,
    stockCount: 8,
    shortDesc: "Diseño clásico de competencia adaptado para el uso en calle. Fabricado en Italia.",
    bgFrom: "#121218",
    bgTo: "#1e1e28",
  },
  {
    id: "enkei-rpf1-17",
    name: "Enkei RPF1 17\"",
    brand: "Enkei",
    category: "rines",
    price: 720000,
    originalPrice: 840000,
    rating: 4.8,
    reviewCount: 187,
    badge: "flash-deal",
    discountPct: 14,
    tags: ["17\"", "Competencia", "5x100"],
    specs: ["17\"", "5x100", "Aluminio forjado"],
    specsTable: [
      { key: "Diámetro",      value: "17 pulgadas" },
      { key: "Patrón",        value: "5x100" },
      { key: "Material",      value: "MAT Aluminio forjado" },
      { key: "Peso",          value: "6.2 kg/ud" },
    ],
    inStock: true,
    stockCount: 6,
    shortDesc: "Uno de los rines más livianos del mercado. Favorito entre quienes hacen track days.",
    bgFrom: "#101018",
    bgTo: "#1a1a28",
  },
  {
    id: "rial-milano-15",
    name: "Rial Milano 15\"",
    brand: "Rial",
    category: "rines",
    price: 350000,
    rating: 4.3,
    reviewCount: 112,
    tags: ["15\"", "Acero", "4x108"],
    specs: ["15\"", "4x108", "Aluminio fundido"],
    specsTable: [
      { key: "Diámetro",      value: "15 pulgadas" },
      { key: "Patrón",        value: "4x108" },
    ],
    inStock: true,
    stockCount: 16,
    shortDesc: "Elegante diseño europeo a un precio accesible. Perfecto para sedanes compactos.",
    bgFrom: "#141414",
    bgTo: "#202020",
  },

  /* ── ACCESORIOS ──────────────────────────────────────────────────── */
  {
    id: "meguiars-kit-limpieza",
    name: "Kit Limpieza Meguiar's Gold",
    brand: "Meguiar's",
    category: "accesorios",
    price: 85000,
    rating: 4.8,
    reviewCount: 789,
    badge: "best-seller",
    tags: ["Limpieza", "Kit", "Cera"],
    specs: ["7 piezas", "Cera", "Microfibra"],
    specsTable: [
      { key: "Contenido",     value: "7 productos" },
      { key: "Incluye",       value: "Champú, Cera, Pulidor, Paños" },
    ],
    inStock: true,
    stockCount: 25,
    shortDesc: "Todo lo que necesitas para dejar tu vehículo impecable en casa.",
    bgFrom: "#0a1a10",
    bgTo: "#122d1a",
  },
  {
    id: "michelin-inflador-digital",
    name: "Inflador Digital Michelin 12600",
    brand: "Michelin",
    category: "accesorios",
    price: 95000,
    rating: 4.6,
    reviewCount: 456,
    badge: "hot",
    tags: ["Inflador", "Digital", "12V"],
    specs: ["Hasta 150 PSI", "12V", "Con manómetro"],
    specsTable: [
      { key: "Presión máx",   value: "150 PSI" },
      { key: "Alimentación",  value: "12V encendedor" },
      { key: "Display",       value: "Digital LCD" },
    ],
    inStock: true,
    stockCount: 18,
    shortDesc: "Infla tu llanta en minutos desde el encendedor del carro. Pantalla digital de fácil lectura.",
    bgFrom: "#1a1a0a",
    bgTo: "#2d2d12",
  },
  {
    id: "extintor-abc-1kg",
    name: "Extintor ABC 1 KG Kidde",
    brand: "Kidde",
    category: "accesorios",
    price: 48000,
    rating: 4.7,
    reviewCount: 234,
    tags: ["Seguridad", "ABC", "1KG"],
    specs: ["1 KG", "ABC", "Polvo seco"],
    specsTable: [
      { key: "Peso",          value: "1 Kg" },
      { key: "Tipo",          value: "ABC Polvo seco" },
      { key: "Norma",         value: "ICONTEC 1668" },
    ],
    inStock: true,
    stockCount: 40,
    shortDesc: "Extintor obligatorio en Colombia. Certificado ICONTEC. Fácil de instalar.",
    bgFrom: "#1a0505",
    bgTo: "#2d0808",
  },
  {
    id: "armorall-original-473ml",
    name: "Armor All Original 473ml",
    brand: "Armor All",
    category: "accesorios",
    price: 32000,
    rating: 4.5,
    reviewCount: 567,
    badge: "hot",
    tags: ["Protector", "Interior", "473ml"],
    specs: ["473ml", "Interior", "UV Protect"],
    specsTable: [
      { key: "Volumen",       value: "473ml" },
      { key: "Uso",           value: "Interior y exterior" },
      { key: "Protección",    value: "UV" },
    ],
    inStock: true,
    stockCount: 60,
    shortDesc: "El protector más vendido del mundo. Rejuvenece plásticos y protege del sol.",
    bgFrom: "#001a10",
    bgTo: "#002d1a",
  },
  {
    id: "kit-herramientas-basico",
    name: "Kit Herramientas Básico 32 pzs",
    brand: "Stanley",
    category: "accesorios",
    price: 125000,
    originalPrice: 149000,
    rating: 4.6,
    reviewCount: 312,
    badge: "flash-deal",
    discountPct: 16,
    tags: ["Herramientas", "32 piezas", "Auto"],
    specs: ["32 piezas", "Acero CrV", "Maletín"],
    specsTable: [
      { key: "Piezas",        value: "32" },
      { key: "Material",      value: "Acero cromo vanadio" },
      { key: "Incluye",       value: "Llaves, destornilladores, alicates" },
    ],
    inStock: true,
    stockCount: 14,
    shortDesc: "El kit esencial para emergencias viales y mantenimiento básico del vehículo.",
    bgFrom: "#101018",
    bgTo: "#1a1a28",
  },
];

/* ── Helpers ─────────────────────────────────────────────────────────── */
export function getProductById(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return ALL_PRODUCTS.filter((p) => p.category === category);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return ALL_PRODUCTS
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  llantas:     "Llantas",
  lubricantes: "Lubricantes",
  baterias:    "Baterías",
  rines:       "Rines",
  accesorios:  "Accesorios",
};
